import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
    "../../packages/ui/src/**/*.{ts,tsx}",
  ],
  safelist: [
    "bg-surface-1", "bg-surface-2", "bg-surface-3", "bg-surface-4",
    "bg-surface-5", "bg-surface-6", "bg-surface-7", "bg-surface-8",
    "shadow-surface-1", "shadow-surface-2", "shadow-surface-3", "shadow-surface-4",
    "shadow-surface-5", "shadow-surface-6", "shadow-surface-7", "shadow-surface-8",
  ],
  theme: {
    extend: {
      fontFamily: {
        inter: ['Inter', 'ui-sans-serif', 'system-ui', '-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', 'Roboto', 'sans-serif'],
      },
      colors: {
        void: '#fafafa',
        'deep-charcoal': '#ffffff',
        'graphite-700': '#ffffff',
        'graphite-600': '#f5f5f5',
        'graphite-500': '#e5e5e5',
        'graphite-400': '#d4d4d4',
        'slate-300': '#737373',
        'slate-200': '#525252',
        'ash-50': '#171717',
        'ember-red': '#dc2626',
        'ember-dark': '#fef2f2',
        'mint-signal': '#16a34a',
        'sky-signal': '#7c3aed',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        hover: 'hsl(var(--accent))',
        active: 'hsl(var(--accent))',
        'surface-1': '#fafafa',
        'surface-2': '#f5f5f5',
        'surface-3': '#f0f0f0',
        'surface-4': '#ebebeb',
        'surface-5': '#e5e5e5',
        'surface-6': '#e0e0e0',
        'surface-7': '#d9d9d9',
        'surface-8': '#d1d1d1',
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
        cards: '12px',
        badges: '6px',
        inputs: '8px',
        modals: '16px',
        buttons: '8px',
        cardlarge: '20px',
        buttonpill: '86px',
      },
      fontSize: {
        caption: ['11px', { lineHeight: '1.45', letterSpacing: '0.8px' }],
        body: ['16px', { lineHeight: '1.5', letterSpacing: '0.1px' }],
        subheading: ['18px', { lineHeight: '1.4', letterSpacing: '0.06px' }],
        'heading-sm': ['24px', { lineHeight: '1.33', letterSpacing: '-0.05px' }],
        heading: ['32px', { lineHeight: '1.2', letterSpacing: '-0.06px' }],
        'heading-lg': ['56px', { lineHeight: '1.1', letterSpacing: '-0.11px' }],
        display: ['64px', { lineHeight: '1', letterSpacing: '-0.13px' }],
      },
      spacing: {
        '8': '8px',
        '16': '16px',
        '24': '24px',
        '32': '32px',
        '40': '40px',
        '48': '48px',
        '56': '56px',
        '64': '64px',
        '80': '80px',
        '96': '96px',
        '120': '120px',
        '224': '224px',
      },
      boxShadow: {
        'surface-1': '0 1px 2px rgba(0,0,0,0.04)',
        'surface-2': '0 2px 4px rgba(0,0,0,0.06)',
        'surface-3': '0 4px 8px rgba(0,0,0,0.08)',
        'surface-4': '0 6px 12px rgba(0,0,0,0.1)',
        'surface-5': '0 8px 16px rgba(0,0,0,0.12)',
        'surface-6': '0 12px 24px rgba(0,0,0,0.14)',
        'surface-7': '0 16px 32px rgba(0,0,0,0.16)',
        'surface-8': '0 24px 48px rgba(0,0,0,0.2)',
        'xl-dark': 'rgba(0,0,0,0.08) 0px 4px 40px 8px, rgba(0,0,0,0.06) 0px 0px 0px 1px, rgba(255,255,255,0.9) 0px 0.5px 0px 0px inset',
        'xl-soft': 'rgba(255,255,255,0.6) 0px 0px 40px 20px, rgba(255,255,255,0.9) 0px 0.5px 0px 0px inset',
      },
      animation: {
        'enter': 'page_fade-in-up 0.4s cubic-bezier(0.23, 1, 0.32, 1) forwards',
        'pulse-glow': 'pulse-glow 3s ease-in-out infinite',
      },
      keyframes: {
        'page_fade-in-up': {
          '0%': { opacity: '0', transform: 'translateY(12px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'pulse-glow': {
          '0%, 100%': { opacity: '0.4' },
          '50%': { opacity: '0.8' },
        },
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
